import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule, MatCheckboxModule,
   MatInputModule, MatAutocompleteModule,
    MatDatepickerModule, MatFormFieldModule,
     MatRadioModule, MatSelectModule,
      MatSliderModule, MatSlideToggleModule,
       MatMenuModule, MatSidenavModule,
        MatToolbarModule, MatListModule,
         MatGridListModule, MatCardModule,
          MatStepperModule, MatTabsModule,
           MatExpansionModule, MatButtonToggleModule,
            MatChipsModule, MatIconModule, MatProgressSpinnerModule,
             MatProgressBarModule, MatDialogModule, MatTooltipModule,
              MatSnackBarModule, MatTableModule,
               MatSortModule, MatPaginatorModule } from '@angular/material';


               import { NgbModule, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';


@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatRadioModule,
    NgbModule,
    MatSelectModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatStepperModule,
    MatTabsModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    NgbModule,
    MatFormFieldModule,
    MatRadioModule,
    MatSelectModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatStepperModule,
    MatTabsModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
  ],
  schemas: [ NO_ERRORS_SCHEMA ]
})
export class AppMateiralModule {

 }
